/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import java.sql.Connection;

import java.sql.PreparedStatement;


import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author varsh
 */
public class DeleteBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBooks
     */
    public DeleteBook() {
        initComponents();
    }
     
       
    
public void getIssueBookDetails(){

int bookId= Integer.parseInt(txt_bookID.getText());
int studentId = Integer.parseInt( txt_studentID.getText());

try{
Connection con = DBConnection.getConnection();
String sql = " select*from issue_bookdetails where book_id=? and student_id=? and status=?";

PreparedStatement pst = con.prepareStatement(sql);
pst.setInt(1,bookId);
pst.setInt(2,studentId);
pst.setString(3,"pending");

ResultSet rs = pst.executeQuery();
if(rs.next()){

lbl_issueId.setText(rs.getString("id"));
lbl_bookName.setText(rs.getString("book_name"));
lbl_studentName.setText(rs.getString("student_name"));
lbl_issueDate.setText(rs.getString("issue_date")); 
lbl_dueDate.setText(rs.getString("due_date")); 
lbl_bookError.setText("");
}  else{
     lbl_issueId.setText("");
     lbl_bookName.setText("");
     lbl_studentName.setText("");
     lbl_issueDate.setText(""); 
     lbl_dueDate.setText("");
     lbl_bookError.setText("no record found");
     
          }
     }catch (Exception e){
         e.printStackTrace();
  }
      
}


public boolean returnBook(){

 boolean isReturned = false;
int bookId= Integer.parseInt(txt_bookID.getText());
int studentId = Integer.parseInt( txt_studentID.getText());

try{
Connection con = DBConnection.getConnection();
String sql = " update issue_bookdetails set status=? where student_id=? and book_id=? and status=?";

PreparedStatement pst = con.prepareStatement(sql);
pst.setString(1,"returned");
pst.setInt(2, studentId);
pst.setInt(3,bookId);
pst.setString(4,"pending");


int rowCount = pst.executeUpdate();
if (rowCount >0){
isReturned =true;
}else{
isReturned=false;
}
}catch(Exception e){
e.printStackTrace();
}
return isReturned;
}  

            

 
public void updateBookCount(){
int bookId = Integer.parseInt(txt_bookID.getText());
try{
Connection con = DBConnection.getConnection();
String sql = " update book_details set quantity = quantity +1 where book_id=?";
PreparedStatement pst =con.prepareStatement(sql);
pst.setInt(1, bookId);

int rowCount = pst.executeUpdate();

if (rowCount>0){
JOptionPane.showMessageDialog(this,"book count updated");
    
}else{
JOptionPane.showMessageDialog(this,"can't update book count ");
}}catch (Exception e){
e.printStackTrace();
}
}
 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle5 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle8 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_bookError = new javax.swing.JLabel();
        lbl_dueDate = new javax.swing.JLabel();
        txt_bookName = new javax.swing.JLabel();
        txt_duedate = new javax.swing.JLabel();
        txt_issueId = new javax.swing.JLabel();
        lbl_issueId = new javax.swing.JLabel();
        lbl_studentName = new javax.swing.JLabel();
        lbl_issueDate = new javax.swing.JLabel();
        txt_issuedate = new javax.swing.JLabel();
        txt_studentName = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_studentID = new app.bolivia.swing.JCTextField();
        txt_bookID = new app.bolivia.swing.JCTextField();
        txt_bookId = new javax.swing.JLabel();
        txt_studentId = new javax.swing.JLabel();
        rSMaterialButtonRectangle6 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle7 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HP Simplified Hans", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Return Book ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -20, 410, 90));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 0, 0));
        rSMaterialButtonRectangle1.setText("Log out ");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel3.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, -10, 120, -1));

        jLabel2.setFont(new java.awt.Font("MV Boli", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle3.setText("Home");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle4.setText("Student Portal");
        rSMaterialButtonRectangle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle4ActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle5.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle5.setText("Manage books");
        rSMaterialButtonRectangle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle5ActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle8.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle8.setText("Issued Books");
        rSMaterialButtonRectangle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle8ActionPerformed(evt);
            }
        });

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle2.setText("Issue Book");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSMaterialButtonRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSMaterialButtonRectangle5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSMaterialButtonRectangle4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSMaterialButtonRectangle8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSMaterialButtonRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangle4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangle5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangle8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMaterialButtonRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 710, 40));

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("HP Simplified", 3, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel3.setText("Book Details");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 330, -1));

        lbl_bookError.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        jPanel5.add(lbl_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 220, 30));

        lbl_dueDate.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        jPanel5.add(lbl_dueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 200, 30));

        txt_bookName.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        txt_bookName.setText("   Book Name:");
        jPanel5.add(txt_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, -1));

        txt_duedate.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        txt_duedate.setText("Due Date:");
        jPanel5.add(txt_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 120, -1));

        txt_issueId.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        txt_issueId.setText("     Issue ID:");
        jPanel5.add(txt_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 140, -1));

        lbl_issueId.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        jPanel5.add(lbl_issueId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, 30));

        lbl_studentName.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        jPanel5.add(lbl_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 200, 30));

        lbl_issueDate.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        jPanel5.add(lbl_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 190, 30));

        txt_issuedate.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        txt_issuedate.setText("Issue Date:");
        jPanel5.add(txt_issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 130, -1));

        txt_studentName.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        txt_studentName.setText("Student Name:");
        jPanel5.add(txt_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, -1));

        lbl_bookName.setFont(new java.awt.Font("HP Simplified Hans", 2, 24)); // NOI18N
        jPanel5.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 210, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 500, 640));

        jLabel4.setFont(new java.awt.Font("HP Simplified", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel4.setText("Return Book ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 360, -1));

        txt_studentID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));
        txt_studentID.setPlaceholder("Please enter Student ID .");
        txt_studentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentIDFocusLost(evt);
            }
        });
        txt_studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 490, 240, -1));

        txt_bookID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 102, 0)));
        txt_bookID.setPlaceholder("Please enter Book ID...");
        txt_bookID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIDFocusLost(evt);
            }
        });
        txt_bookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 380, 240, -1));

        txt_bookId.setFont(new java.awt.Font("HP Simplified", 2, 24)); // NOI18N
        txt_bookId.setForeground(new java.awt.Color(255, 102, 51));
        txt_bookId.setText("Book ID:");
        jPanel1.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 110, -1));

        txt_studentId.setFont(new java.awt.Font("HP Simplified", 2, 24)); // NOI18N
        txt_studentId.setForeground(new java.awt.Color(255, 102, 51));
        txt_studentId.setText(" Student ID: ");
        jPanel1.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 150, -1));

        rSMaterialButtonRectangle6.setBackground(new java.awt.Color(0, 0, 255));
        rSMaterialButtonRectangle6.setBorder(new javax.swing.border.MatteBorder(null));
        rSMaterialButtonRectangle6.setText("Find");
        rSMaterialButtonRectangle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, -1, -1));

        rSMaterialButtonRectangle7.setBackground(new java.awt.Color(255, 102, 0));
        rSMaterialButtonRectangle7.setBorder(new javax.swing.border.MatteBorder(null));
        rSMaterialButtonRectangle7.setText("Return Book");
        rSMaterialButtonRectangle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 710, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 900));

        setSize(new java.awt.Dimension(1527, 890));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        SignupPage signup= new SignupPage();
    signup.setVisible(true);
    dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void rSMaterialButtonRectangle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle5ActionPerformed
       ManageBooks books= new ManageBooks();
       books.setVisible(true);
       dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle5ActionPerformed

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
      HomePage home= new HomePage();
      home.setVisible(true);
      dispose();// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    private void rSMaterialButtonRectangle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle4ActionPerformed
       ManageStudents student= new ManageStudents();
       student.setVisible(true);
       dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle4ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        HomePage home= new HomePage();
        home.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txt_studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_studentIDActionPerformed

    private void txt_bookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIDActionPerformed
     
    }//GEN-LAST:event_txt_bookIDActionPerformed
    
    private void txt_bookIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIDFocusLost
  
     
    }//GEN-LAST:event_txt_bookIDFocusLost

    private void txt_studentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIDFocusLost
      
    }//GEN-LAST:event_txt_studentIDFocusLost
    
    private void rSMaterialButtonRectangle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle6ActionPerformed
         getIssueBookDetails();    

    }//GEN-LAST:event_rSMaterialButtonRectangle6ActionPerformed

    private void rSMaterialButtonRectangle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle7ActionPerformed
                if(returnBook()==true){
                 JOptionPane.showMessageDialog(this,"book returned successfully");
                 updateBookCount();
                 }else{ 
                 JOptionPane.showMessageDialog(this,"book returned successfully");
}        
    }//GEN-LAST:event_rSMaterialButtonRectangle7ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
 IssueBooks issue = new IssueBooks();
        issue.setVisible(true);
        dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle8ActionPerformed
 IssuedBooks issued = new IssuedBooks();
          issued.setVisible(true);
           dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle8ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_bookError;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_dueDate;
    private javax.swing.JLabel lbl_issueDate;
    private javax.swing.JLabel lbl_issueId;
    private javax.swing.JLabel lbl_studentName;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle6;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle7;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle8;
    private app.bolivia.swing.JCTextField txt_bookID;
    private javax.swing.JLabel txt_bookId;
    private javax.swing.JLabel txt_bookName;
    private javax.swing.JLabel txt_duedate;
    private javax.swing.JLabel txt_issueId;
    private javax.swing.JLabel txt_issuedate;
    private app.bolivia.swing.JCTextField txt_studentID;
    private javax.swing.JLabel txt_studentId;
    private javax.swing.JLabel txt_studentName;
    // End of variables declaration//GEN-END:variables
}
